
version: 2.1

parameters:
  run-pod-lint:
    type: boolean
    default: true

  run-tests:
    type: boolean
    default: true

  allow-warnings:
    type: string
    default: "YES"

jobs:
  tests:
  macos:
    xcode: 13.1.0
    steps:
      - checkout

      - name: Setup Code Climate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Install test dependencies
          run: |
            bundle install

      - name: Run Cocoapods' linter
          # Warnings might be allowed in versions where Instructions continue to support
          # deprecated methods.
          run: |
            if [ "<<parameters.allow-warnings>>" == "YES" ]; then
              pod lib lint --allow-warnings;
            else
              pod lib lint;
            fi
          when: <<parameters.run-pod-lint>>

      - name: Build example projects
          run: |
            bundle exec fastlane build_examples

      - name: Run tests
          run: |
            bundle exec fastlane test_all
          when: <<parameters.run-tests>>

      - name: Convert and upload coverage
          environment:
            CC_TEST_REPORTER_ID: postgres://conductor:@localhost:5432/conductor_test
          run: |
            slather coverage -x --build-directory Build/
            ./cc-test-reporter after-build --coverage-input-type cobertura "Tests/cobertura.xml"

      - store_artifacts:
          path: "Examples/Example/Snapshot Tests/Supporting Files/Snapshots/FailureDiffs/"
          destination: "failure-diffs"
          when: on_fail
            and:
              - on_fail
              - equal: [true, <<parameters.run-tests>>]

workflows:
  all-tests:
    jobs:
      - tests
