
version: 2.1

jobs:
  tests:
    parameters:
      run-pod-lint:
        type: boolean
        default: true

      run-tests:
        type: boolean
        default: true

      allow-warnings:
        type: string
        default: "YES"

    macos:
      xcode: 13.1.0

    steps:
      - checkout

      - run:
          name: Setup Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - run:
          name: Install test dependencies
          command: |
            bundle install

      - when:
          condition: <<parameters.run-pod-lint>>
          steps:
            - run:
                name: Run Cocoapods' linter
                # Warnings might be allowed in versions where Instructions continue to support
                # deprecated methods.
                command: |
                  if [ "<<parameters.allow-warnings>>" == "YES" ]; then
                    pod lib lint --allow-warnings;
                  else
                    pod lib lint;
                  fi


      - run:
          name: Build example projects
          command: |
            bundle exec fastlane build_examples

      - when:
          condition: <<parameters.run-tests>>
          steps:
            - run:
                name: Run tests
                command: |
                  bundle exec fastlane test_all

      - run:
          name: Convert and upload coverage
          environment:
            CC_TEST_REPORTER_ID: postgres://conductor:@localhost:5432/conductor_test
          command: |
            slather coverage -x --build-directory Build/
            ./cc-test-reporter after-build --coverage-input-type cobertura "Tests/cobertura.xml"

      - when:
          condition:
            and:
              - on_fail
              - equal: [true, <<parameters.run-tests>>]
          steps:
            - store_artifacts:
                path: "Examples/Example/Snapshot Tests/Supporting Files/Snapshots/FailureDiffs/"
                destination: "failure-diffs"


workflows:
  all-tests:
    jobs:
      - tests
