name: build

on:
  push:
    branches:
    - main
    - github-actions
    - 'release-**'
  pull_request:
    branches:
    - main
    - github-actions
    - 'release-**'

env:
  # Expected to be used withint scripts.
  LANG: en_US.UTF-8

  PROJECT: "Instructions.xcodeproj"
  EXAMPLE_PROJECT: "Examples/Instructions Example.xcodeproj"
  APPEX_EXAMPLE_PROJECT: "Examples/Instructions App Extensions Example.xcodeproj"

  SCHEME: "Instructions"
  EXAMPLE_SCHEME: "Instructions Example"
  APPEX_EXAMPLE_SCHEME: "Instructions App Extensions Example"

  SDK: "iphonesimulator15.0"

  ALLOW_WARNINGS: "NO"

  DESTINATION: "OS=15.0,name=iPhone 13 Pro"

  # Wether or not to perform certain steps.
  run_pod_lint: true
  build_example: true
  build_app_extension_example: true
  run_tests: true

jobs:
  test:
    name: Build, lint & test
    runs-on: macos-11

    steps:
      - name: Switch Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_13.1.app

      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install test dependencies
        run: |
          bundle install

      - name: Run Cocoapods' linter
        if: env.run_pod_lint == 'true'
        # Warnings might be allowed in versions where Instructions continue to support
        # deprecated methods.
        run: |
          if [ $ALLOW_WARNINGS == "YES" ]; then
            pod lib lint --allow-warnings;
          else
            pod lib lint;
          fi

      - name: Build example projects
        if: env.build_example == 'true'
        run: |
          bundle exec fastlane build_examples

      - name: Run tests
        if: env.run_tests == 'true'
        run: |
          bundle exec fastlane test_all

      - name: Upload Failure Diffs
        uses: actions/upload-artifact@v2
        if: failure() && env.run_tests == 'true'
        with:
          name: FailureDiffs
          path: "${{github.workspace}}/Examples/Example/Snapshot\ Tests/Supporting\ Files/Snapshots/FailureDiffs/"

      - name: Convert and upload coverage
        uses: paambaati/codeclimate-action@v2.6.0
        if: env.run_tests == 'true'
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: "slather coverage -x --build-directory Build/"
          coverageLocations: "${{github.workspace}}/Tests/cobertura.xml:cobertura"
