name: package-management

on:
  push:
    branches:
    - main
    - github-actions
    - 'release-**'
  pull_request:
    branches:
    - main
    - github-actions
    - 'release-**'

env:
  LANG: en_US.UTF-8

  SDK: "iphonesimulator15.0"
  DESTINATION: "OS=15.0,name=iPhone 13 Pro"

  TEST_DIRECTORY: "PackageTest"

jobs:
  test:
    name: Check installation
    runs-on: macos-11

    steps:
      - name: Switch Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_13.1.app

      - name: Check out test repository
        uses: actions/checkout@v2
        with:
          repository: "ephread/InstructionsPackageTest"
          path: ${{ env.TEST_DIRECTORY }}

      - name: Change Directory
        run: |
          cd $TEST_DIRECTORY

      - name: Install test dependencies
        run: |
          bundle install

      - name: Test CocoaPods import
        run: |
          bundle exec fastlane test_cocoapods

      - name: Test Carthage import
        run: |
          bundle exec fastlane test_carthage

      - name: Test SwiftPM import
        run: |
          bundle exec fastlane test_swiftpm
